# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QQMusic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QQMusic
    pod 'Alamofire', '~> 4.0.1'
    pod 'Kingfisher', '~> 3.1.3'
    pod 'SnapKit', '~> 3.0.0'
    
    pod 'SwiftyJSON', '~> 3.1.1'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    

end
